Testing:
- changed-files:
  - any-glob-to-any-file: 'src/tests/*'

GitHub-Action:
- changed-files:
  - any-glob-to-any-file: '.github/workflows/*'

python:
- changed-files:
  - any-glob-to-any-file: 'src/python/*'

javascript:
- changed-files:
  - any-glob-to-any-file: 'src/*.js'

html:
- changed-files:
  - any-glob-to-any-file: 'src/*.html'

css:
- changed-files:
  - any-glob-to-any-file: 'src/*.css'

dependencies:
- changed-files:
  - any-glob-to-any-file: 'requirements.txt'
  - any-glob-to-any-file: 'package.json'
  - any-glob-to-any-file: 'package-lock.json'

documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'
  - any-glob-to-any-file: '*.md'
