name: Auto Assign Reviewer
on:
  pull_request:
    types: [opened, reopened]

jobs:
    specific_review_requested:
        runs-on: ubuntu-latest
        if: ${{ github.event.requested.name == 'wxboysuper'}}
        steps:
          - run: echo 'A review from WeatherboySuper was requested'
