name: Auto Assign Reviewer
on:
  pull_request:
    types: [ready_for_review]

jobs:
    specific_review_requested:
        runs-on: ubuntu-latest
        steps:
          - run: echo 'A review from WeatherboySuper was requested'
