name: Run all tests

on: 
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

permissions:
    contents: read
    pull-requests: write
    checks: write

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: ./src

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"

        - name: Print Working Directory
          run: |
            pwd
            ls -la
            echo "PYTHONPATH=$PYTHONPATH"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r ../requirements.txt

        - name: Set PYTHONPATH
          run: |
            echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
            echo "Updated PYTHONPATH=$PYTHONPATH:$(pwd)"

        - name: Test with unittest
          run: |
            coverage run --omit=*/test_* -m unittest discover tests
            pwd

        - name: Create Coverage Report
          run: |
            coverage report -m
            coverage xml

        - name: DeepSource Test Coverage
          uses: deepsourcelabs/test-coverage-action@master
          with: 
            key: python
            coverage-file: ../coverage.xml
            dsn: ${{ secrets.DEEPSOURCE_DSN }}
